{% set name = "pyedr" %}
{% set version = "0.8.0" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.org/packages/source/{{ name[0] }}/{{ name }}/pyedr-{{ version }}.tar.gz
  sha256: 2d119dc32cd0b0b2a14584626c2349b9dbad132a6bfed32723fe841ed5857fd0

build:
  noarch: python
  script: {{ PYTHON }} -m pip install . -vv
  number: 1

requirements:
  host:
    - python {{ python_min }}
    - versioningit
    - pip
  run:
    - python >={{ python_min }}
    - numpy
    - tqdm
    - mda-xdrlib

test:
  imports:
    - pyedr
  commands:
    - pip check
  requires:
    - pip
    - python {{ python_min }}

about:
  home: https://github.com/MDAnalysis/panedr
  summary: Read and manipulate Gromacs energy files
  license: LGPL-2.1-or-later
  license_file: LICENSE.txt

extra:
  recipe-maintainers:
    - IAlibay
    - BFedder
    - jbarnoud
    - orbeckst
