{% set name = "pyedr" %}
{% set version = "0.7.2" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.io/packages/source/{{ name[0] }}/{{ name }}/pyedr-{{ version }}.tar.gz
  sha256: 8a02b7d94f97f99083c489568f7816ee8ed37e2efca0c1ba3a2e4b83e932d5b9

build:
  noarch: python
  script: {{ PYTHON }} -m pip install . -vv
  number: 0

requirements:
  host:
    - python >=3.6
    - pbr
    - pip
  run:
    - python >=3.6
    - numpy
    - pbr
    - tqdm
    - mda-xdrlib

test:
  imports:
    - pyedr
  commands:
    - pip check
  requires:
    - pip

about:
  home: https://github.com/MDAnalysis/panedr
  summary: Read and manipulate Gromacs energy files
  license: LGPL-2.1-or-later
  license_file: LICENSE.txt

extra:
  recipe-maintainers:
    - IAlibay
    - BFedder
    - jbarnoud
    - orbeckst
